### ISSUE TITLE
Clean up and restructure the design document on unstructured (Assigned to Till)

### ISSUE THREAD

**Issue by mbianco** [GridTools/_GT_Tasks#31]
Not publishing it, but be the baseline for the implementation and further discussions

**Comment by tehrengruber** [comment]
The new document can be found here: https://git.cscs.ch/tille/gt4py-unstructured-syntax-design/-/blob/master/language_reference/language_reference.rst

It is a draft version in the style of a language reference that should be expanded and enhanced in the future.
